import {
    CakeSlice,
    Candy,
    ChevronsUpDown,
    Coffee,
    CupSoda,
    DollarSign,
    Donut,
    Eye,
    EyeOff,
    IceCream,
    Loader2,
    Lollipop,
    Martini,
    Menu,
    Milk,
    Shell,
    Snowflake,
    Star,
    Utensils,
    Popcorn,
    Bean,
    ChevronsLeft,
    ChevronLeft,
    ChevronRight,
    ChevronsRight,
    X,
    ArrowUpDown,
    PlusCircle,
    Check,
} from 'lucide-react';

import Cereals from '../Icons/Cereals';
import Chips from '../Icons/Chips';
import Chocolate from '../Icons/Chocolate';
import ChocolateBar from '../Icons/ChocolateBar';

export const Icons = {
    spinner: Loader2,
    menu: Menu,
    star: Star,
    chevronsUpDown: ChevronsUpDown,
    dollarSign: DollarSign,
    cakeSlice: CakeSlice,
    lollipop: Lollipop,
    donut: Donut,
    eye: Eye,
    eyeOff: EyeOff,
    martini: Martini,
    milk: Milk,
    coffee: Coffee,
    cupSoda: CupSoda,
    candy: Candy,
    utensils: Utensils,
    snowflake: Snowflake,
    iceCream: IceCream,
    shell: Shell,
    cereals: Cereals,
    chips: Chips,
    chocolate: Chocolate,
    chocolateBar: ChocolateBar,
    popcorn: Popcorn,
    bean: Bean,
    chevronsLeft: ChevronsLeft,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    chevronsRight: ChevronsRight,
    x: X,
    arrowUpDown: ArrowUpDown,
    plusCircle: PlusCircle,
    check: Check,
};
