import {
    Loader2,
    LogOut,
    ChevronLeftCircle,
    ChevronsUpDown,
    Check,
    ChevronLeft,
    ChevronsLeft,
    ChevronRight,
    ChevronsRight,
    Menu,
    ArrowUpDown,
    SquareStack,
    MoreHorizontal,
} from 'lucide-react';

export const Icons = {
    spinner: Loader2,
    logout: LogOut,
    arrowCircleLeft: ChevronLeftCircle,
    chevronsUpDown: ChevronsUpDown,
    check: Check,
    menu: Menu,
    squareStack: SquareStack,
    more: MoreHorizontal,
    arrowUpDown: ArrowUpDown,
    chevronLeft: ChevronLeft,
    chevronsLeft: ChevronsLeft,
    chevronRight: ChevronRight,
    chevronsRight: ChevronsRight,
};
